### PR TITLE
fix(frontend/tests): assign Purchaser group to admin mocks (carve-out follow-up)

### PR DESCRIPTION
**Pull request by cristim**
## Summary

- Three frontend test suites missed by PR #924's fix wave were breaking CI on every open PR against `feat/multicloud-web-frontend`
- Root cause: each suite had admin session fixtures that pre-dated the Purchaser group carve-out from issues #923/#924
- Fix: add `PURCHASER_GROUP_ID` to admin mocks + add missing `getExecuteMode`/`clearExecuteMode` stubs to the recommendations mock factory

## Root cause (points to #924)

PR #924 carved out `execute:purchases`, `approve-any:purchases`, and `retry-any:purchases` from `admin:*` and required Purchaser group membership for those verbs. It fixed four test suites but missed these three:

1. `execute-mode-toggle.test.ts`: `mockUser('admin')` produced `{ role: 'admin' }` with no `groups` array. `canAccess('execute-any', 'purchases')` falls back to `isAdmin()`, which requires `ADMINISTRATORS_GROUP_ID` in `user.groups`. Without a groups array, `isAdmin()` returned false and the execute-mode toggle never rendered (3 tests failed).

2. `purchase-execution-toast.test.ts`: the `jest.mock('../recommendations')` factory was missing `getExecuteMode` and `clearExecuteMode`. `app.ts` calls both in `handleExecutePurchase` (introduced in the #289/#924 wave). Every single-record test threw `TypeError: getExecuteMode is not a function` at line 328 of `app.ts` before reaching the toast assertions (12 tests failed).

3. `recommendations.test.ts`: the default state mock had `groups: ['00000000-0000-5000-8000-000000000001']` (Administrators only). `canAccess('execute-any', 'purchases')` is NOT a carved-out verb so it calls `isAdmin()` (not `isPurchaser()`), meaning admin-group membership alone caused the execute-mode toggle to render. Three tests expecting the approval-required note saw the toggle text instead.

## Per-suite fix

- **execute-mode-toggle.test.ts**: Import `ADMINISTRATORS_GROUP_ID` and `PURCHASER_GROUP_ID` from `../permissions`; `mockUser('admin')` now produces `groups: [ADMINISTRATORS_GROUP_ID, PURCHASER_GROUP_ID]` (mirrors the auto-migration pattern from #924). Non-admin roles produce `groups: []`. **3 tests updated.**

- **purchase-execution-toast.test.ts**: Add `getExecuteMode: jest.fn().mockReturnValue('')` and `clearExecuteMode: jest.fn()` to the recommendations mock factory. The approval path default (`''`) leaves all existing toast assertions unaffected. **1 mock factory updated, 12 previously-failing tests now pass.**

- **recommendations.test.ts**: The three approval-required note tests override `getCurrentUser` to a non-admin user (`groups: []`) so the approval note renders instead of the execute-mode toggle. A paired restore call / `afterEach` restores the admin user to prevent mock state from leaking into sibling describe blocks. **3 tests updated.**

## Test plan

- [x] `npx jest src/__tests__/execute-mode-toggle.test.ts` - 6/6 pass
- [x] `npx jest src/__tests__/purchase-execution-toast.test.ts` - 21/21 pass
- [x] `npx jest src/__tests__/recommendations.test.ts` - 367/367 pass
- [x] `npx tsc --noEmit` - clean
- [ ] CI green on `feat/multicloud-web-frontend` after merge

### CODE REVIEW

**Comment by cristim** [comment]
@coderabbitai review
